define({
    root: {
        // Statistics container
        streamingStatistics: "Streaming Statistics",
        totalPackets: "Total Packets",
        packetRate: "PacketRate",
        packetsLostTotal: "Total packets lost",
        packetsLostPerSecond: "Packets lost / s",
        totalSent: "Total sent",
        sentRate: "Sent rate",
        bitrate: "Bitrate",
        ping: "Ping",
        totalLatency: "Total latency",
        encodeLatency: "Encoder Latency",
        encodeLatencyMax: "Encode latency max",
        transportLatency: "Transport latency",
        decodeLatency: "Decoder latency",
        fecPercentage: "Fec percentage",
        fecFailureTotal: "Fec failure total",
        fecFailureInSecond: "Fec failure / s",
        clientFPS: "Client FPS",
        serverFPS: "Server FPS",
        packets: "Packets",
        packetss: "Packets / s",
        batteries: "Batteries",
        headset: "Headset",
        left: "Left",
        right: "Right",
        // Performance graphs tab
        performanceGraphs: "Performance graphs",
        performanceNetwork: "Network",
        performanceTranscode: "Transcode",
        performanceRender: "Render",
        performanceIdle: "Idle",
        performanceGameRender: "Game Render",
        performanceServerCompositor: "Server Compositor",
        performanceEncode: "Encode",
        performanceSend: "Send (+ Receive)",
        performanceDecode: "Decode",
        performanceClientCompositor: "Client Compositor",
        performanceClientVsync: "Client Vsync",
        performanceLatency: "Latency",
        performanceTotalLatency: "Total Latency",
        performanceFramerate: "Framerate",
        performanceServer: "Server",
        performanceClient: "Client",
        performanceNoDateCaptured: "No data captured yet",
    },
    it: true,
    sl: true,
    es: true,
    fr: true,
    ja: true,
    zh: true,
    ru: true,
    bg: true,
    de: true,
    nl: true,
    ko: true,
});
